#+TITLE: Active Damping of Rotating Positioning Platforms using Force Feedback
:DRAWER:
#+LATEX_CLASS: ISMA_USD2020
#+OPTIONS: toc:nil
#+STARTUP: overview

#+DATE:
#+AUTHOR:

#+LATEX_HEADER_EXTRA: \author[1,3] {T. Dehaeze}
#+LATEX_HEADER_EXTRA: \author[1,2] {C. Collette}

#+LATEX_HEADER_EXTRA: \affil[1] {Precision Mechatronics Laboratory\NewLineAffil University of Liege, Belgium \NewAffil}
#+LATEX_HEADER_EXTRA: \affil[2] {BEAMS Department\NewLineAffil Free University of Brussels, Belgium \NewAffil}
#+LATEX_HEADER_EXTRA: \affil[3] {European Synchrotron Radiation Facility \NewLineAffil Grenoble, France e-mail: \textbf{thomas.dehaeze@esrf.fr}}

#+LATEX_HEADER_EXTRA: \bibliographystyle{IEEEtran}

#+LATEX_HEADER: \usepackage{amsmath,amssymb,amsfonts, cases}
#+LATEX_HEADER: \usepackage{algorithmic, graphicx, textcomp}
#+LATEX_HEADER: \usepackage{xcolor, import, hyperref}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage[USenglish]{babel}

#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usetikzlibrary{shapes.misc}

#+LATEX_HEADER: \setcounter{footnote}{1}
#+LATEX_HEADER: \input{config.tex}
:END:

* LaTeX Config                                                      :noexport:
#+begin_src latex :tangle config.tex

#+end_src

* Build                                                             :noexport:
#+NAME: startblock
#+BEGIN_SRC emacs-lisp :results none
  (add-to-list 'org-latex-classes
               '("ISMA_USD2020"
                 "\\documentclass{ISMA_USD2020}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
#+END_SRC

* Abstract                                                            :ignore:
#+BEGIN_EXPORT latex
\abstract{
    Abstract text to be done
}
#+END_EXPORT

* Introduction
<<sec:introduction>>
** Establish the importance of the research topic                    :ignore:
# Active Damping + Rotating System

Controller Poles are shown by black crosses (
\begin{tikzpicture} \node[cross out, draw=black, minimum size=1ex, line width=2pt, inner sep=0pt, outer sep=0pt] at (0, 0){}; \end{tikzpicture}
).

** Applications of active damping                                    :ignore:
# Link to previous paper / tomography

# Such as the Nano-Active-Stabilization-System currently in development at the ESRF cite:dehaeze18_sampl_stabil_for_tomog_exper.

** Current active damping techniques                                 :ignore:
# IFF, DVF

** Describe a gap in the research                                    :ignore:
# No literature on rotating systems => gyroscopic effects

** Describe the paper itself / the problem which is addressed        :ignore:

Due to gyroscopic effects, the guaranteed robustness properties of Integral Force Feedback do not hold.
Either the control architecture can be slightly modfied or mechanical changes in the system can be performed.

** Introduce Each part of the paper                                  :ignore:

This paper has been published
The Matlab code that was use to obtain the results are available in cite:dehaeze20_activ_dampin_rotat_posit_platf.

* Dynamics of Rotating Positioning Platforms
** Model of a Rotating Positioning Platform
# Introduce the fact that we need a simple system representing the rotating aspect
To study how the rotation of positioning platforms does affect the use of force feedback, a simple model is developed.

# Simplest system where gyroscopic forces can be studied
It represents an X-Y positioning stage on top of a Rotating Stage and is schematically represented in Figure ref:fig:system.

# Explain the frames (inertial frame x,y, rotating frame u,v)
Two frames of reference are used:
- $(\vec{i}_x, \vec{i}_y, \vec{i}_z)$ is an inertial frame
- $(\vec{i}_u, \vec{i}_v, \vec{i}_w)$ is a frame fixed on the Rotating Stage with its origin align with the rotation axis

# Present the system, parameters, assumptions (small displacements, perfect spindle)
The rotating stage is supposed to be ideal, meaning it is infinitely rigid and induces a rotation $\theta(t) = \Omega t$ where $\Omega$ is the rotational speed in $\si{\radian\per\second}$.

# X-Y Stage
The parallel X-Y positioning stage consists of two orthogonal actuators represented by the three following elements in parallel:
- A spring with a stiffness $k$ in $\si{\newton\per\meter}$
- A dashpot with a damping coefficient $c$ in $\si{\newton\per\meter\second}$
- An ideal force source $F_u, F_v$ in $\si{\newton}$

# Payload
The X-Y stage is supporting a payload with a payload with a mass $m$ in $\si{\kilo\gram}$.
The position of the payload is represented by $(d_u, d_v)$ expressed in the rotating frame $(\vec{i}_u, \vec{i}_v)$.

#+name: fig:system
#+caption: Schematic of the studied System
#+attr_latex: :scale 1
[[file:figs/system.pdf]]

** Equations of Motion
To obtain of equation of motion for the system represented in Figure ref:fig:system, the Lagrangian equations are used:
#+name: eq:lagrangian_equations
\begin{equation}
  \frac{d}{dt} \left( \frac{\partial L}{\partial \dot{q}_i} \right) + \frac{\partial D}{\partial \dot{q}_i} - \frac{\partial L}{\partial q_i} = Q_i
\end{equation}
with $L = T - V$ is the Lagrangian, $D$ is the dissipation function, and $Q_i$ is the generalized force associated with the generalized variable $[q_1\ q_2] = [d_u\ d_v]$:
#+name: eq:energy_functions_lagrange
\begin{subequations}
  \begin{align}
    T & = \frac{1}{2} m \left( \left( \dot{d}_u - \Omega d_v \right)^2 + \left( \dot{d}_v + \Omega d_u \right)^2 \right) \\
    V & = \frac{1}{2} k \left( {d_u}^2 + {d_v}^2 \right) \\
    D & = \frac{1}{2} c \left( \dot{d}_u{}^2 + \dot{d}_v{}^2 \right) \\
    Q_1 &= F_u, \quad Q_2 = F_v
  \end{align}
\end{subequations}

Substituting equations eqref:eq:energy_functions_lagrange into eqref:eq:lagrangian_equations gives the two coupled differential equations:
#+name: eq:eom_coupled
\begin{subequations}
  \begin{align}
    m \ddot{d}_u + c \dot{d}_u + ( k - m \Omega ) d_u &= F_u + 2 m \Omega \dot{d}_v \\
    m \ddot{d}_v + c \dot{d}_v + ( k \underbrace{-\,m \Omega}_{\text{Centrif.}} ) d_v &= F_v \underbrace{-\,2 m \Omega \dot{d}_u}_{\text{Coriolis}}
  \end{align}
\end{subequations}

# Explain Gyroscopic effects
The rotation of the XY positioning platform induces two Gyroscopic effects:
- Coriolis Forces: that adds coupling between the two orthogonal controlled directions
- Centrifugal forces: that can been seen as negative stiffness

** Transfer Functions in the Laplace domain
To study the dynamics of the system, the differential equations of motions eqref:eq:eom_coupled are transformed in the Laplace domain and the transfer functions from $[F_u,\ F_v]$ to $[d_u,\ d_v]$ are obtained:
#+name: eq:Gd_mimo_tf
\begin{equation}
  \begin{bmatrix} d_u \\ d_v \end{bmatrix} = \bm{G}_d \begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}

with $\bm{G}_d$ a $2 \times 2$ transfer function matrix
#+name: eq:Gd_m_k_c
\begin{equation}
  \bm{G}_{d} =
  \begin{bmatrix}
    \frac{ms^2 + cs + k - m \Omega^2}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} & \frac{2 m \Omega s}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} \\
    \frac{-2 m \Omega s}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} & \frac{ms^2 + cs + k - m \Omega^2}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2}
  \end{bmatrix}
\end{equation}

One can verify that without rotation ($\Omega = 0$) the system becomes equivalent as to two uncoupled one degree of freedom mass-spring-damper systems:
#+name: eq:oem_no_rotation
\begin{subequations}
  \begin{align}
    d_u &= \frac{1}{m s^2 + cs + k} F_u \\
    d_v &= \frac{1}{m s^2 + cs + k} F_v
  \end{align}
\end{subequations}

** Change of Variables / Parameters for the study

# Change of variables
In order to make this study less dependent on the system parameters, the following change of variable is performed:
- $\omega_0 = \sqrt{\frac{k}{m}}$: Natural frequency of the mass-spring system in $\si{\radian/\s}$
- $\xi = \frac{c}{2 \sqrt{k m}}$: Damping ratio

The transfer function matrix eqref:eq:Gd_m_k_c becomes equal to
#+name: eq:Gd_w0_xi_k
\begin{equation}
\bm{G}_{d} =
  \frac{1}{k}
  \begin{bmatrix}
    \frac{\frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
    \frac{- 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
  \end{bmatrix}
\end{equation}

# Parameters
During the rest of this study, the following parameters are used for numerical analysis
- $\omega_0 = \SI{1}{\radian\per\second}$, $\xi = 0.025 = \SI{2.5}{\percent}$
- $k = \SI{1}{N/m}$, $m = \SI{1}{kg}$, $c = \SI{0.05}{\newton\per\meter\second}$

# Say that these parameters are not realist but will be used to draw conclusions "relatively"

** System Dynamics and Campbell Diagram
# Campbell Diagram
The poles of $\bm{G}_d$ are the complex solutions $p$ of
\begin{equation}
  \left( \frac{p^2}{{\omega_0}^2} + 2 \xi \frac{p}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{p}{\omega_0} \right)^2 = 0
\end{equation}

Supposing small damping ($\xi \ll 1$), two pairs of complex conjugate poles are obtained:
#+name: eq:pole_values
\begin{subequations}
  \begin{align}
    p_{+} &= - \xi \omega_0 \left( 1 + \frac{\Omega}{\omega_0} \right) \pm j \left( \omega_0 + \Omega \right) \\
    p_{-} &= - \xi \omega_0 \left( 1 - \frac{\Omega}{\omega_0} \right) \pm j \left( \omega_0 - \Omega \right)
  \end{align}
\end{subequations}

When the rotation speed in non-null, the resonance frequency is split into two pairs of complex conjugate poles.
As the rotation speed increases, $p_{+}$ goes to higher frequencies and $p_{-}$ to lower frequencies.

# The system goes unstable at some frequency w0
When the rotational speed $\Omega$ reaches $\omega_0$, the real part $p_{-}$ is positive meaning the system becomes unstable.
The stiffness of the X-Y stage is too low to hold to rotating payload hence the instability.
Stiff positioning platforms should be used if high rotational speeds or heavy payloads are used.

This is graphically represented with the Campbell Diagram in Figure ref:fig:campbell_diagram.

#+name: fig:campbell_diagram
#+caption: Campbell Diagram : Evolution of the complex and real parts of the system's poles as a function of the rotational speed $\Omega$
#+attr_latex: :environment subfigure :width 0.4\linewidth :align c
| file:figs/campbell_diagram_real.pdf     | file:figs/campbell_diagram_imag.pdf          |
| <<fig:campbell_diagram_real>> Real Part | <<fig:campbell_diagram_imag>> Imaginary Part |

# Bode Plots for different ratio W/w0
Looking at the transfer function matrix $\bm{G}_d$ eqref:eq:Gd_w0_xi_k, one can see it has two distinct terms that can be studied separately:
- the direct (diagonal) terms
- the coupling (off-diagonal) terms

The bode plot of the direct and coupling terms are shown in Figure ref:fig:plant_compare_rotating_speed for several rotational speed $\Omega$.

# Describe the dynamics: without rotation
Without rotation, the dynamics of the direct terms is equivalent to the dynamics of a one degree of freedom mass spring damper system and the coupling terms are null.
As the rotational speed increases, the pair of complex conjugate poles is separated into two pairs of complex conjugate poles, one going to lower frequencies and the other to higher frequencies.
When the

#+name: fig:plant_compare_rotating_speed
#+caption: Bode Plots for $\bm{G}_d$ for several rotational speed $\Omega$
#+attr_latex: :environment subfigure :width 0.45\linewidth :align c
| file:figs/plant_compare_rotating_speed_direct.pdf                             | file:figs/plant_compare_rotating_speed_coupling.pdf                               |
| <<fig:plant_compare_rotating_speed_direct>> Direct Terms $d_u/F_u$, $d_v/F_v$ | <<fig:plant_compare_rotating_speed_coupling>> Coupling Terms $d_v/F_u$, $d_u/F_v$ |

In the rest of this study, $\Omega < \omega_0$

* Decentralized Integral Force Feedback
** System Schematic and Control Architecture
Force Sensors are added in series with the actuators as shown in Figure [[fig:system_iff]].

# Reference to IFF control

# Explain what "decentralized" means

# => we consider the system has two SISO systems for the control

# Say that we will use the same controllers for the two directions

#+name: fig:system_iff
#+caption: System with Force Sensors in Series with the Actuators. Decentralized Integral Force Feedback is used
#+attr_latex: :scale 1
[[file:figs/system_iff.pdf]]

** Plant Dynamics
The forces measured by the force sensors are equal to:
#+name: eq:measured_force
\begin{equation}
  \begin{bmatrix} f_{u} \\ f_{v} \end{bmatrix} =
  \begin{bmatrix} F_u \\ F_v \end{bmatrix} - (c s + k)
  \begin{bmatrix} d_u \\ d_v \end{bmatrix}
\end{equation}

Re-injecting eqref:eq:Gd_w0_xi_k into eqref:eq:measured_force yields:
#+name: eq:Gf_mimo_tf
\begin{equation}
  \begin{bmatrix} f_{u} \\ f_{v} \end{bmatrix} = \bm{G}_{f} \begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}
with $\bm{G}_f$ a $2 \times 2$ transfer function matrix
#+name: eq:Gf
\begin{equation}
  \bm{G}_{f} = \begin{bmatrix}
  \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{- \left( 2 \xi \frac{s}{\omega_0} + 1 \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
  \frac{\left( 2 \xi \frac{s}{\omega_0} + 1 \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
\end{bmatrix}
\end{equation}

# Explain the two real zeros => change of gain but not of phase
# The alternating poles and zeros properties of collocated IFF holds
# but additional real zeros are added

The zeros of the diagonal terms of $\bm{G}_f$ are equal to (neglecting the damping)
\begin{subequations}
  \begin{align}
    z_c &= \pm j \omega_0 \sqrt{\frac{1}{2} \sqrt{8 \frac{\Omega^2}{{\omega_0}^2} + 1} + \frac{\Omega^2}{{\omega_0}^2} + \frac{1}{2} } \label{eq:iff_zero_cc} \\
    z_r &= \pm   \omega_0 \sqrt{\frac{1}{2} \sqrt{8 \frac{\Omega^2}{{\omega_0}^2} + 1} - \frac{\Omega^2}{{\omega_0}^2} - \frac{1}{2} } \label{eq:iff_zero_real}
  \end{align}
\end{subequations}

The frequency of the two complex conjugate zeros $z_c$ eqref:eq:iff_zero_cc is between the frequency of the two pairs of complex conjugate poles $p_{-}$ and $p_{+}$ eqref:eq:pole_values.
This is the expected behavior of a collocated pair of actuator and sensor.

However, the two real zeros $z_c$ induces an increase of +2 of the slope without change of phase (Figure [[fig:plant_iff_compare_rotating_speed]]).
This represents non-minimum phase behavior.

# Explain physically why the real zeros


# Show that the low frequency gain is no longer zero
The low frequency gain, for $\Omega < \omega_0$, is no longer zero:
#+name: low_freq_gain_iff_plan
\begin{equation}
  \bm{G}_{f0} = \lim_{\omega \to 0} \left| \bm{G}_f (j\omega) \right| = \begin{bmatrix}
  \frac{- \Omega^2}{{\omega_0}^2 - \Omega^2} & 0 \\
  0  & \frac{- \Omega^2}{{\omega_0}^2 - \Omega^2}
\end{bmatrix}
\end{equation}

It increases with the rotational speed $\Omega$.

#+name: fig:plant_iff_compare_rotating_speed
#+caption: Bode plot of $\bm{G}_f$ for several rotational speeds $\Omega$
#+attr_latex: :scale 1
[[file:figs/plant_iff_compare_rotating_speed.pdf]]

** Decentralized Integral Force Feedback

\begin{equation}
  K_F(s) = g \cdot \frac{1}{s}
\end{equation}

# Problem of zero with a positive real part
Also, as one zero has a positive real part, the *IFF control is no more unconditionally stable*.
This is due to the fact that the zeros of the plant are the poles of the closed loop system with an infinite gain.
Thus, for some finite IFF gain, one pole will have a positive real part and the system will be unstable.

# General explanation for the Root Locus Plot
# MIMO root locus: gain is simultaneously increased for both decentralized controllers
# Explain the circles, crosses and black crosses (poles of the controller)
# transmission zeros

#+name: fig:root_locus_pure_iff
#+caption: Root Locus for the Decentralized Integral Force Feedback
#+attr_latex: :scale 1
[[file:figs/root_locus_pure_iff.pdf]]

# IFF is usually known for its guaranteed stability (add reference)
# This is not the case anymore due to gyroscopic effects

# Physical Interpretation

At low frequency, the gain is very large and thus no force is transmitted between the payload and the rotating stage.
This means that at low frequency, the system is decoupled (the force sensor removed) and thus the system is unstable.

# Introduce next two sections where either:
# - IFF is modified to deal with this low frequency behavior
# - physical system is modified

* Integral Force Feedback with High Pass Filters
** Modification of the Control Low
# Reference to Preumont where its done


# Equation with the new control law
\begin{equation}
  K_{F}(s) = g \cdot \frac{1}{s} \cdot \underbrace{\frac{s/\omega_i}{1 + s/\omega_i}}_{\text{HPF}} = g \cdot \frac{1}{s + \omega_i}
\end{equation}


# Explain why it is usually done and why it is done here: the problem is the high gain at low frequency => high pass filter


** Feedback Analysis
# Explain what do we mean for Loop Gain (loop gain for the decentralized loop)

# Explain that now the low frequency loop gain does not reach a gain more than 1 (if g not so high)

#+name: fig:loop_gain_modified_iff
#+caption: Bode Plot of the Loop Gain for IFF with and without the HPF
#+attr_latex: :scale 1
[[file:figs/loop_gain_modified_iff.pdf]]

# Not the system can be stable for small values of g
# Actually, the system becomes unstable for g > ... => it has been verified
\begin{equation}
  g_\text{max} = \omega_i \left( \frac{{\omega_0}^2}{\Omega^2} - 1 \right) \label{eq:iff_gmax}
\end{equation}

#+name: fig:root_locus_modified_iff
#+caption: Root Locus for IFF with and without the HPF
#+attr_latex: :scale 1
[[file:figs/root_locus_modified_iff.pdf]]

** Optimal Cut-Off Frequency

# Controller: two parameters: gain and wi

# Try few wi

# Small wi seems to allow more damping to be added
# but the gain is limited to small values

# Trade off

#+name: fig:root_locus_wi_modified_iff
#+caption: Root Locus for several HPF cut-off frequencies $\omega_i$
#+attr_latex: :scale 1
[[file:figs/root_locus_wi_modified_iff.pdf]]

# Study this trade-off

# Explain how the figure is obtained

# for small wi => gain limited
# for large wi => damping limited
# wi = 0.1 w0 is chosen

#+name: fig:mod_iff_damping_wi
#+caption: Attainable damping ratio $\xi_\text{cl}$ as a function of the HPF cut-off frequency. Corresponding control gain $g_\text{opt}$ and $g_\text{max}$ are also shown
#+attr_latex: :scale 1
[[file:figs/mod_iff_damping_wi.pdf]]

* Integral Force Feedback with Parallel Springs
** Stiffness in Parallel with the Force Sensor
# Zeros = remove force sensor
# We want to have stable zeros => add stiffnesses in parallel

#+name: fig:system_parallel_springs
#+caption: System with added springs in parallel with the actuators
#+attr_latex: :scale 1
[[file:figs/system_parallel_springs.pdf]]

# Maybe add the fact that this is equivalent to amplified piezo for instance
# Add reference to cite:souleille18_concep_activ_mount_space_applic

** Plant Dynamics

We define an adimensional parameter $\alpha$, $0 \le \alpha < 1$, that describes the proportion of the stiffness in parallel with the actuator and force sensor:
\begin{subequations}
  \begin{align}
    k_p &= \alpha k \\
    k_a &= (1 - \alpha) k
  \end{align}
\end{subequations}

The overall stiffness $k$ stays constant:
\begin{equation}
  k = k_a + k_p
\end{equation}

# Equations: sensed force
#+name: eq:Gk_mimo_tf
\begin{equation}
\begin{bmatrix} f_u \\ f_v \end{bmatrix} =
\bm{G}_k
\begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}

#+name: eq:Gk
\begin{equation}
\bm{G}_k =
\begin{bmatrix}
  \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} + \alpha \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{- \left( 2 \xi \frac{s}{\omega_0} + 1 - \alpha \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
  \frac{\left( 2 \xi \frac{s}{\omega_0} + 1 - \alpha \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} + \alpha \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
\end{bmatrix}
\end{equation}

# News terms with \alpha are added
# w0 and xi are the same as before => only the zeros are changing and not the poles.

** Effect of the Parallel Stiffness on the Plant Dynamics
# Negative Stiffness due to rotation => the stiffness should be larger than that

# For kp < negative stiffness => real zeros => non-minimum phase
# For kp > negative stiffness => complex conjugate zeros => minimum phase
\begin{equation}
  \begin{aligned}
    \alpha > \frac{\Omega^2}{{\omega_0}^2} \\
    \Leftrightarrow k_p > m \Omega^2
  \end{aligned}
\end{equation}

#+name: fig:plant_iff_kp
#+caption: Bode Plot of $f_u/F_u$ without parallel spring, with parallel springs with stiffness $k_p < m \Omega^2$ and $k_p > m \Omega^2$
#+attr_latex: :scale 1
[[file:figs/plant_iff_kp.pdf]]

# Location of the zeros as a function of kp => maybe to complex
# Do we talk about siso zeros of mimo (transmission zeros)?

# Try to show that we don't have anymore real zeros that was making the system non-minimum phase

# Show that it is the case on the root locus

#+name: fig:root_locus_iff_kp
#+caption: Root Locus for IFF without parallel spring, with parallel springs with stiffness $k_p < m \Omega^2$ and $k_p > m \Omega^2$
#+attr_latex: :scale 1
[[file:figs/root_locus_iff_kp.pdf]]

# For kp > m Omega => unconditionally stable

** Optimal Parallel Stiffness
# Attainable damping generally proportional to the distance between the poles and zeros (add reference, probably preumont)
# The zero is the poles of the system without the force sensors => w0 = sqrt(kp/m) +/- Omega ?? => seems not true
# Thus, small kp is wanted: kp close to m Omega^2 should give the optimal damping but is not acceptable for robustness reasons


# Large Stiffness decreases the attainable damping

# Example with kp = 5 m Omega

#+name: fig:root_locus_iff_kps_opt
#+caption: Root Locus for IFF when parallel stiffness is used
#+attr_latex: :environment subfigure :width 0.49\linewidth :align c
| file:figs/root_locus_iff_kps.pdf                 | file:figs/root_locus_opt_gain_iff_kp.pdf                                          |
| <<fig:root_locus_iff_kps>> Three values of $k_p$ | <<fig:root_locus_opt_gain_iff_kp>> $k_p = 5 m \Omega^2$, optimal damping is shown |


* Direct Velocity Feedback                                          :noexport:
** System Schematic and Control Architecture
# Basic Idea of DVF


# Equation with the control law: pure gain
\begin{equation}
  K_V(s) = g
\end{equation}

#+name: fig:system_dvf
#+caption: System with relative velocity sensors and with decentralized controllers $K_V$
#+attr_latex: :scale 1
[[file:figs/system_dvf.pdf]]

# Equivalent System is the same as Figure 1 (as increasing "c")

# Thus very much equivalent as adding passive elements such as dashpot

** Equations

# Write the equations

\begin{equation}
\begin{bmatrix} v_u \\ v_v \end{bmatrix} =
\bm{G}_v
\begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}

\begin{equation}
\begin{bmatrix} v_u \\ v_v \end{bmatrix} =
\frac{1}{k} \frac{1}{G_{vp}}
\begin{bmatrix}
   G_{vz} & G_{vc} \\
  -G_{vc} & G_{vz}
\end{bmatrix}
\begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}
With:
\begin{subequations}
  \begin{align}
    G_{vp} &= \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2 \\
    G_{vz} &= s \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) \\
    G_{vc} &= 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0}
  \end{align}
\end{subequations}

# Show that the rotation have somehow less impact on the plant than for IFF


# Eventually add a bode plot to show the effect of the rotation speed


** Relative Direct Velocity Feedback

# Unconditionally stable

# Arbitrary Damping can be added to the poles

#+name: fig:root_locus_dvf
#+caption: Root Locus for Decentralized Direct Velocity Feedback for several rotational speeds $\Omega$
#+attr_latex: :scale 1
[[file:figs/root_locus_dvf.pdf]]

* Comparison of the Proposed Active Damping Techniques for Rotating Positioning Stages
** Physical Comparison



** Attainable Damping

#+name: fig:comp_root_locus
#+caption: Root Locus for the three proposed decentralized active damping techniques: IFF with HFP, IFF with parallel springs, and relative DVF
#+attr_latex: :scale 1
[[file:figs/comp_root_locus.pdf]]


** Transmissibility and Compliance


# IFF with HPF and IFF with kp give very similar results

# Both techniques provides very good amount of damping

# IFF degrades the compliance at low frequency (add reference)

# Relative DVF degrades the transmissibility at high frequency
# The roll-off is -1 instead of -2

#+name: fig:comp_active_damping
#+caption: Comparison of the three proposed Active Damping Techniques
#+attr_latex: :environment subfigure :width 0.45\linewidth :align c
| file:figs/comp_compliance.pdf            | file:figs/comp_transmissibility.pdf      |
| <<fig:comp_compliance>> Transmissibility | <<fig:comp_transmissibility>> Compliance |

# #+name: fig:comp_compliance
# #+caption: Figure caption
# #+attr_latex: :scale 1
# [[file:figs/comp_compliance.pdf]]

# #+name: fig:comp_transmissibility
# #+caption: Figure caption
# #+attr_latex: :scale 1
# [[file:figs/comp_transmissibility.pdf]]

* Conclusion
<<sec:conclusion>>

* Acknowledgment
:PROPERTIES:
:UNNUMBERED: t
:END:

* Bibliography                                                        :ignore:
\bibliography{ref.bib}
