#+TITLE: Active Damping of Rotating Positioning Platforms using Force Feedback
:DRAWER:
#+LATEX_CLASS: ISMA_USD2020
#+OPTIONS: toc:nil
#+STARTUP: overview

#+DATE:
#+AUTHOR:

#+LATEX_HEADER_EXTRA: \author[1,3] {T. Dehaeze}
#+LATEX_HEADER_EXTRA: \author[1,2] {C. Collette}

#+LATEX_HEADER_EXTRA: \affil[1] {Precision Mechatronics Laboratory\NewLineAffil University of Liege, Belgium \NewAffil}
#+LATEX_HEADER_EXTRA: \affil[2] {BEAMS Department\NewLineAffil Free University of Brussels, Belgium \NewAffil}
#+LATEX_HEADER_EXTRA: \affil[3] {European Synchrotron Radiation Facility \NewLineAffil Grenoble, France e-mail: \textbf{thomas.dehaeze@esrf.fr}}

#+LATEX_HEADER_EXTRA: \bibliographystyle{IEEEtran}

#+LATEX_HEADER: \usepackage{amsmath,amssymb,amsfonts, cases}
#+LATEX_HEADER: \usepackage{algorithmic, graphicx, textcomp}
#+LATEX_HEADER: \usepackage{xcolor, import, hyperref}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage[USenglish]{babel}

#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usetikzlibrary{shapes.misc,arrows,arrows.meta}

#+LATEX_HEADER: \setcounter{footnote}{1}
#+LATEX_HEADER: \input{config.tex}
:END:

* LaTeX Config                                                      :noexport:
#+begin_src latex :tangle config.tex

#+end_src

* Build                                                             :noexport:
#+NAME: startblock
#+BEGIN_SRC emacs-lisp :results none
  (add-to-list 'org-latex-classes
               '("ISMA_USD2020"
                 "\\documentclass{ISMA_USD2020}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
#+END_SRC

* Abstract                                                            :ignore:
#+BEGIN_EXPORT latex
\abstract{
    Abstract text to be done
}
#+END_EXPORT

* Introduction
<<sec:introduction>>
** Establish the importance of the research topic                    :ignore:
# Active Damping + Rotating System


** Applications of active damping                                    :ignore:
# Link to previous paper / tomography

# Such as the Nano-Active-Stabilization-System currently in development at the ESRF cite:dehaeze18_sampl_stabil_for_tomog_exper.

** Current active damping techniques                                 :ignore:
# IFF, DVF

** Describe a gap in the research                                    :ignore:
# No literature on rotating systems => gyroscopic effects

** Describe the paper itself / the problem which is addressed        :ignore:

Due to gyroscopic effects, the guaranteed robustness properties of Integral Force Feedback do not hold.
Either the control architecture can be slightly modified or mechanical changes in the system can be performed.

** Introduce Each part of the paper                                  :ignore:

This paper has been published
The Matlab code that was use to obtain the results are available in cite:dehaeze20_activ_dampin_rotat_posit_platf.

* Dynamics of Rotating Positioning Platforms
<<sec:dynamics>>
** Model of a Rotating Positioning Platform
# Introduce the fact that we need a simple system representing the rotating aspect
In order to study how the rotation of a positioning platforms does affect the use of force feedback, a simple model of an X-Y positioning stage on top of a rotating stage is developed.
# Simplest system where gyroscopic forces can be studied
The model is schematically represented in Figure ref:fig:system and forms the simplest system where gyroscopic forces can be studied.

# Present the system, parameters, assumptions (small displacements, perfect spindle)
The rotating stage is supposed to be ideal, meaning it induces a perfect rotation $\theta(t) = \Omega t$ where $\Omega$ is the rotational speed in $\si{\radian\per\second}$.

# X-Y Stage
The parallel X-Y positioning stage consists of two orthogonal actuators represented by three elements in parallel:
- a spring with a stiffness $k$ in $\si{\newton\per\meter}$
- a dashpot with a damping coefficient $c$ in $\si{\newton\per\meter\second}$
- an ideal force source $F_u, F_v$

# Payload
A payload with a mass $m$ in $\si{\kilo\gram}$ is mounted on the rotating X-Y stage.

# Explain the frames (inertial frame x,y, rotating frame u,v)
Two reference frames are used:
- an inertial frame $(\vec{i}_x, \vec{i}_y, \vec{i}_z)$
- a uniform rotating frame $(\vec{i}_u, \vec{i}_v, \vec{i}_w)$ rigidly fixed on top of the rotating stage. $\vec{i}_w$ is aligned with the rotation axis

The position of the payload is represented by $(d_u, d_v)$ expressed in the rotating frame.

#+name: fig:system
#+caption: Schematic of the studied System
#+attr_latex: :scale 1
[[file:figs/system.pdf]]

** Equations of Motion
To obtain of equation of motion for the system represented in Figure ref:fig:system, the Lagrangian equations are used:
#+name: eq:lagrangian_equations
\begin{equation}
  \frac{d}{dt} \left( \frac{\partial L}{\partial \dot{q}_i} \right) + \frac{\partial D}{\partial \dot{q}_i} - \frac{\partial L}{\partial q_i} = Q_i
\end{equation}
with $L = T - V$ the Lagrangian, $D$ the dissipation function, and $Q_i$ the generalized force associated with the generalized variable $\begin{bmatrix}q_1 & q_2\end{bmatrix} = \begin{bmatrix}d_u & d_v\end{bmatrix}$.

The constant rotation in the $(\vec{i}_x, \vec{i}_y)$ plane is here disregarded as it is imposed by the rotating stage.
#+name: eq:energy_functions_lagrange
\begin{subequations}
  \begin{align}
    T & = \frac{1}{2} m \left( \left( \dot{d}_u - \Omega d_v \right)^2 + \left( \dot{d}_v + \Omega d_u \right)^2 \right) \\
    V & = \frac{1}{2} k \left( {d_u}^2 + {d_v}^2 \right) \\
    D & = \frac{1}{2} c \left( \dot{d}_u{}^2 + \dot{d}_v{}^2 \right) \\
    Q_1 &= F_u, \quad Q_2 = F_v
  \end{align}
\end{subequations}

Substituting equations eqref:eq:energy_functions_lagrange into eqref:eq:lagrangian_equations gives the two coupled differential equations:
#+name: eq:eom_coupled
\begin{subequations}
  \begin{align}
    m \ddot{d}_u + c \dot{d}_u + ( k - m \Omega^2 ) d_u &= F_u + 2 m \Omega \dot{d}_v \\
    m \ddot{d}_v + c \dot{d}_v + ( k \underbrace{-\,m \Omega^2}_{\text{Centrif.}} ) d_v &= F_v \underbrace{-\,2 m \Omega \dot{d}_u}_{\text{Coriolis}}
  \end{align}
\end{subequations}

# Explain Gyroscopic effects
The constant rotation of the system induces two Gyroscopic effects:
- Centrifugal forces: that can been seen as added negative stiffness along $\vec{i}_u$ and $\vec{i}_v$
- Coriolis Forces: that couples the motion in the two orthogonal directions

One can verify that without rotation ($\Omega = 0$) the system becomes equivalent as to two uncoupled one degree of freedom mass-spring-damper systems:
#+name: eq:oem_no_rotation
\begin{subequations}
  \begin{align}
    m \ddot{d}_u + c \dot{d}_u + k d_u &= F_u \\
    m \ddot{d}_v + c \dot{d}_v + k d_v &= F_v
  \end{align}
\end{subequations}

** Transfer Functions in the Laplace domain
To study the dynamics of the system, the differential equations of motions eqref:eq:eom_coupled are transformed in the Laplace domain and the transfer function matrix from $\begin{bmatrix}F_u & F_v\end{bmatrix}$ to $\begin{bmatrix}d_u & d_v\end{bmatrix}$ is obtained:
#+name: eq:Gd_mimo_tf
\begin{equation}
  \begin{bmatrix} d_u \\ d_v \end{bmatrix} = \bm{G}_d \begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}
with $\bm{G}_d$ a $2 \times 2$ transfer function matrix
#+name: eq:Gd_m_k_c
\begin{equation}
  \bm{G}_{d} =
  \begin{bmatrix}
    \frac{ms^2 + cs + k - m \Omega^2}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} & \frac{2 m \Omega s}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} \\
    \frac{-2 m \Omega s}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2} & \frac{ms^2 + cs + k - m \Omega^2}{\left( m s^2 + cs + k - m \Omega^2 \right)^2 + \left( 2 m \Omega s \right)^2}
  \end{bmatrix}
\end{equation}

# Change of variables
To simply the analysis, the following change of variable is performed:
- $\omega_0 = \sqrt{\frac{k}{m}}$: Undamped natural frequency of the mass-spring system in $\si{\radian/\s}$
- $\xi = \frac{c}{2 \sqrt{k m}}$: Damping ratio

The transfer function matrix eqref:eq:Gd_m_k_c becomes equal to
#+name: eq:Gd_w0_xi_k
\begin{equation}
\bm{G}_{d} =
  \frac{1}{k}
  \begin{bmatrix}
    \frac{\frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
    \frac{- 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2}}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
  \end{bmatrix}
\end{equation}

# Parameters
For all the numerical analysis in this study, $\omega_0 = \SI{1}{\radian\per\second}$, $k = \SI{1}{\newton\per\meter}$ and $\xi = 0.025 = \SI{2.5}{\percent}$.
# Say that these parameters are not realist but will be used to draw conclusions "relatively"
Even tough no system with such parameters will be encountered in practice, conclusions will be drawn relative to these parameters such that they can be generalized to any other parameter.

** System Dynamics and Campbell Diagram
# Poles computation
The poles of $\bm{G}_d$ are the complex solutions $p$ of
\begin{equation}
  \left( \frac{p^2}{{\omega_0}^2} + 2 \xi \frac{p}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{p}{\omega_0} \right)^2 = 0
\end{equation}

Supposing small damping ($\xi \ll 1$), two pairs of complex conjugate poles are obtained:
#+name: eq:pole_values
\begin{subequations}
  \begin{align}
    p_{+} &= - \xi \omega_0 \left( 1 + \frac{\Omega}{\omega_0} \right) \pm j \omega_0 \left( 1 + \frac{\Omega}{\omega_0} \right) \\
    p_{-} &= - \xi \omega_0 \left( 1 - \frac{\Omega}{\omega_0} \right) \pm j \omega_0 \left( 1 - \frac{\Omega}{\omega_0} \right)
  \end{align}
\end{subequations}

# Campbell Diagram
The real part and complex part of these two pairs of complex conjugate poles are represented in Figure ref:fig:campbell_diagram as a function of the rotational speed $\Omega$.
As the rotational speed increases, $p_{+}$ goes to higher frequencies and $p_{-}$ to lower frequencies.
The system becomes unstable for $\Omega > \omega_0$ as the real part of $p_{-}$ is positive.
Physically, the negative stiffness term $-m\Omega^2$ induced by centrifugal forces exceeds the spring stiffness $k$.

In the rest of this study, rotational speeds smaller than the undamped natural frequency of the system are used ($\Omega < \omega_0$).

#+name: fig:campbell_diagram
#+caption: Campbell Diagram : Evolution of the complex and real parts of the system's poles as a function of the rotational speed $\Omega$
#+attr_latex: :environment subfigure :width 0.4\linewidth :align c
| file:figs/campbell_diagram_real.pdf     | file:figs/campbell_diagram_imag.pdf          |
| <<fig:campbell_diagram_real>> Real Part | <<fig:campbell_diagram_imag>> Imaginary Part |

# Bode Plots for different ratio W/w0
Looking at the transfer function matrix $\bm{G}_d$ in Eq. eqref:eq:Gd_w0_xi_k, one can see that the two diagonal (direct) terms are equal and the two off-diagonal (coupling) terms are opposite.
The bode plot of these two distinct terms are shown in Figure ref:fig:plant_compare_rotating_speed for several rotational speeds $\Omega$.
# Rapid Analysis of the dynamics
It is confirmed that the two pairs of complex conjugate poles are further separated as $\Omega$ increases.
For $\Omega > \omega_0$, the low frequency complex conjugate poles $p_{-}$ becomes unstable.

#+name: fig:plant_compare_rotating_speed
#+caption: Bode Plots for $\bm{G}_d$ for several rotational speed $\Omega$
#+attr_latex: :environment subfigure :width 0.45\linewidth :align c
| file:figs/plant_compare_rotating_speed_direct.pdf                             | file:figs/plant_compare_rotating_speed_coupling.pdf                                |
| <<fig:plant_compare_rotating_speed_direct>> Direct Terms $d_u/F_u$, $d_v/F_v$ | <<fig:plant_compare_rotating_speed_coupling>> Coupling Terms $d_v/F_u$, $-d_u/F_v$ |

* Decentralized Integral Force Feedback
<<sec:iff>>
** Force Sensors and Control Architecture
# Description of the control architecture
In order to apply Decentralized Integral Force Feedback to the system, force sensors are added in series with the two actuators (Figure ref:fig:system_iff).
Two identical controllers $K_F$ are added to feedback each of the sensed forces to its collocated actuator.
The control diagram is shown in Figure ref:fig:control_diagram_iff.

# Decentralized aspect + SISO approach

#+attr_latex: :options [t]{0.55\linewidth}
#+begin_minipage
#+name: fig:system_iff
#+caption: System with added Force Sensor in series with the actuators
#+attr_latex: :scale 1 :float nil
[[file:figs/system_iff.pdf]]
#+end_minipage
\hfill
#+attr_latex: :options [t]{0.40\linewidth}
#+begin_minipage
#+name: fig:control_diagram_iff
#+caption: Control Diagram for decentralized IFF
#+attr_latex: :scale 1 :float nil
[[file:figs/control_diagram_iff.pdf]]
#+end_minipage

** Plant Dynamics
The forces measured by the force sensors are equal to:
#+name: eq:measured_force
\begin{equation}
  \begin{bmatrix} f_{u} \\ f_{v} \end{bmatrix} =
  \begin{bmatrix} F_u \\ F_v \end{bmatrix} - (c s + k)
  \begin{bmatrix} d_u \\ d_v \end{bmatrix}
\end{equation}

Re-injecting eqref:eq:Gd_w0_xi_k into eqref:eq:measured_force yields:
#+name: eq:Gf_mimo_tf
\begin{equation}
  \begin{bmatrix} f_{u} \\ f_{v} \end{bmatrix} = \bm{G}_{f} \begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}
with $\bm{G}_f$ a $2 \times 2$ transfer function matrix
#+name: eq:Gf
\begin{equation}
  \bm{G}_{f} = \begin{bmatrix}
  \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{- \left( 2 \xi \frac{s}{\omega_0} + 1 \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
  \frac{\left( 2 \xi \frac{s}{\omega_0} + 1 \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
\end{bmatrix}
\end{equation}

The zeros of the diagonal terms are equal to (neglecting the damping for simplicity)
\begin{subequations}
  \begin{align}
    z_c &= \pm j \omega_0 \sqrt{\frac{1}{2} \sqrt{8 \frac{\Omega^2}{{\omega_0}^2} + 1} + \frac{\Omega^2}{{\omega_0}^2} + \frac{1}{2} } \label{eq:iff_zero_cc} \\
    z_r &= \pm   \omega_0 \sqrt{\frac{1}{2} \sqrt{8 \frac{\Omega^2}{{\omega_0}^2} + 1} - \frac{\Omega^2}{{\omega_0}^2} - \frac{1}{2} } \label{eq:iff_zero_real}
  \end{align}
\end{subequations}

The frequency of the two complex conjugate zeros $z_c$ eqref:eq:iff_zero_cc is between the frequency of the two pairs of complex conjugate poles $p_{-}$ and $p_{+}$ eqref:eq:pole_values.
This is the expected behavior of a collocated pair of actuator and sensor.

However for non-null rotational speeds, two real zeros $z_r$ eqref:eq:iff_zero_real appear in the diagonal terms which represent a non-minimum phase behavior.
This can be seen in the Bode plot of the diagonal terms (Figure ref:fig:plant_iff_compare_rotating_speed) where the magnitude experiences an increase of its slope without any change of phase.

# Show that the low frequency gain is no longer zero
The low frequency gain of $\bm{G}_f$ is no longer zero, and increases with the rotational speed $\Omega$
#+name: low_freq_gain_iff_plan
\begin{equation}
  \lim_{\omega \to 0} \left| \bm{G}_f (j\omega) \right| = \begin{bmatrix}
  \frac{- \Omega^2}{{\omega_0}^2 - \Omega^2} & 0 \\
  0  & \frac{- \Omega^2}{{\omega_0}^2 - \Omega^2}
\end{bmatrix}
\end{equation}

# Explain why do we have this low frequency gain
This low frequency gain can be explained as follows: a constant force induces a small displacement of the mass, which then increases the centrifugal forces measured by the force sensors.
# Another way to explain this low frequency gain is to model the centrifugal forces by a negative stiffness $k_p = -m \Omega^2$ in parallel with both the actuator and force sensor as in Figure ref:fig:system_parallel_springs.

#+name: fig:plant_iff_compare_rotating_speed
#+caption: Bode plot of the diagonal terms of $\bm{G}_f$ for several rotational speeds $\Omega$
#+attr_latex: :scale 1
[[file:figs/plant_iff_compare_rotating_speed.pdf]]

** Decentralized Integral Force Feedback with Pure Integrators
The two IFF controllers $K_F$ are pure integrators
\begin{equation}
  \bm{K}_F(s) = \begin{bmatrix} K_F(s) & 0 \\ 0 & K_F(s) \end{bmatrix}, \quad K_F(s) = g \cdot \frac{1}{s}
\end{equation}
where $g$ is a scalar value representing the gain of the controller.

# General explanation for the Root Locus Plot
In order to see how the controller affects the poles of the closed loop system, the Root Locus is constructed as follows.
The poles of the closed-loop system are drawn in the complex plane as the gain $g$ varies from $0$ to $\infty$ for the two controllers simultaneously.
The closed-loop poles start at the open-loop poles (shown by $\tikz[baseline=-0.6ex] \node[cross out, draw=black, minimum size=1ex, line width=2pt, inner sep=0pt, outer sep=0pt] at (0, 0){};$) for $g = 0$ and coincide with the transmission zeros (shown by $\tikz[baseline=-0.6ex] \draw[line width=2pt, inner sep=0pt, outer sep=0pt] (0,0) circle[radius=3pt];$) as $g \to \infty$.
The direction of increasing gains is shown by the arrows $\tikz[baseline=-0.6ex] \draw[-{Stealth[round]},line width=2pt] (0,0) -- (0.3,0);$.

#+name: fig:root_locus_pure_iff
#+caption: Root Locus for the Decentralized Integral Force Feedback
#+attr_latex: :scale 1
[[file:figs/root_locus_pure_iff.pdf]]

# IFF is usually known for its guaranteed stability (add reference) which is not the case anymore due to gyroscopic effects
Whereas collocated IFF is known for its guaranteed stability, which is the case here for $\Omega = 0$, this property is lost as soon as the rotational speed in non-null due to gyroscopic effects.
This can be seen in the Root Locus (Figure ref:fig:root_locus_pure_iff) where the pole corresponding to the controller is bounded to the right half plane implying closed-loop system instability.

# Physical Interpretation ?
# This instability can be explained by the gyroscopic effects.
# At low frequency, the gain is very large and thus no force is transmitted to the payload.
# This means that at low frequency, the system is decoupled (the force sensor removed) and thus the system is unstable.

# Introduce next two sections
Two system modifications are proposed in the next sections to deal with this stability problem.
Either the control law can be change (Section ref:sec:iff_hpf) or the mechanical system slightly modified (Section ref:sec:iff_kp).

* Integral Force Feedback with High Pass Filters
<<sec:iff_hpf>>
** Modification of the Control Low
# Reference to Preumont where its done


# Equation with the new control law
# Equivalent as to add a HFP or to slightly move the pole to the left
#+NAME: eq:IFF_LHF
\begin{equation}
  K_{F}(s) = g \cdot \frac{1}{s} \cdot \underbrace{\frac{s/\omega_i}{1 + s/\omega_i}}_{\text{HPF}} = g \cdot \frac{1}{s + \omega_i}
\end{equation}

# Explain why it is usually done and why it is done here: the problem is the high gain at low frequency => high pass filter


** Feedback Analysis
# Explain what do we mean for Loop Gain (loop gain for the decentralized loop)

# Explain that now the low frequency loop gain does not reach a gain more than 1 (if g not so high)

#+name: fig:loop_gain_modified_iff
#+caption: Bode Plot of the Loop Gain for IFF with and without the HPF with $\omega_i = 0.1 \omega_0$, $g = 2$ and $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/loop_gain_modified_iff.pdf]]

# Explain how the root locus changes (the pole corresponding to the controller is moved to the left)

# Explain that it is stable for small values of $g$ but at some point, the system goes unstable
# Explain what is the maximum value of the gain
As shown in Figure ref:fig:root_locus_modified_iff, the poles of the closed loop system are stable for $g < g_\text{max}$
\begin{equation}
  g_{\text{max}} = \omega_i \left( \frac{{\omega_0}^2}{\Omega^2} - 1 \right)
\end{equation}

# Small rotational speeds allows to increase the control gain
# Large wi allows more gain but less damping

# Say that this corresponds as to have a low frequency gain of the loop gain less thank 1


#+name: fig:root_locus_modified_iff
#+caption: Root Locus for IFF with and without the HPF, $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/root_locus_modified_iff.pdf]]

** Optimal Control Parameters

# Controller: two parameters: gain and wi
Two parameters can be tuned for the controller eqref:eq:IFF_LHF, the gain $g$ and the frequency of the pole $\omega_i$.

# Try few wi
Root Locus plots for several $\omega_i$ are shown in Figure ref:fig:root_locus_wi_modified_iff.

# Small wi seems to allow more damping to be added
# but the gain is limited to small values

# Trade off

#+name: fig:root_locus_wi_modified_iff
#+caption: Root Locus for several HPF cut-off frequencies $\omega_i$, $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/root_locus_wi_modified_iff.pdf]]

# Study this trade-off
The optimal values of $\omega_i$ and $g$ may be considered as the values for which the closed-loop poles are equally damped.

# Explain how the figure is obtained

# for small wi => gain limited
# for large wi => damping limited
# wi = 0.1 w0 is chosen

#+name: fig:mod_iff_damping_wi
#+caption: Attainable damping ratio $\xi_\text{cl}$ as a function of the HPF cut-off frequency. Corresponding control gain $g_\text{opt}$ and $g_\text{max}$ are also shown
#+attr_latex: :scale 1
[[file:figs/mod_iff_damping_wi.pdf]]

* Integral Force Feedback with Parallel Springs
<<sec:iff_kp>>
** Stiffness in Parallel with the Force Sensor
# Zeros = remove force sensor
# We want to have stable zeros => add stiffnesses in parallel
Stiffness can be added in parallel to the force sensor to counteract the negative stiffness due to centrifugal forces.
If the added stiffness is higher than the maximum negative stiffness, then the poles of the IFF damped system will stay in the (stable) right half-plane.

#+name: fig:system_parallel_springs
#+caption:
#+attr_latex: :scale 1
[[file:figs/system_parallel_springs.pdf]]


# Sensed Force
The forces measured by the force sensors are equal to:
#+name: eq:measured_force_kp
\begin{equation}
  \begin{bmatrix} f_{u} \\ f_{v} \end{bmatrix} =
  \begin{bmatrix} F_u \\ F_v \end{bmatrix} - (c s + k_a)
  \begin{bmatrix} d_u \\ d_v \end{bmatrix}
\end{equation}

# Maybe add the fact that this is equivalent to amplified piezo for instance
# Add reference to cite:souleille18_concep_activ_mount_space_applic
This could represent a system where

** Plant Dynamics

We define an adimensional parameter $\alpha$, $0 \le \alpha < 1$, that describes the proportion of the stiffness in parallel with the actuator and force sensor:
\begin{subequations}
  \begin{align}
    k_p &= \alpha k \\
    k_a &= (1 - \alpha) k
  \end{align}
\end{subequations}

The overall stiffness $k$ stays constant:
\begin{equation}
  k = k_a + k_p
\end{equation}

# Equations: sensed force
#+name: eq:Gk_mimo_tf
\begin{equation}
\begin{bmatrix} f_u \\ f_v \end{bmatrix} =
\bm{G}_k
\begin{bmatrix} F_u \\ F_v \end{bmatrix}
\end{equation}

#+name: eq:Gk
\begin{equation}
\bm{G}_k =
\begin{bmatrix}
  \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} + \alpha \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{- \left( 2 \xi \frac{s}{\omega_0} + 1 - \alpha \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} \\
  \frac{\left( 2 \xi \frac{s}{\omega_0} + 1 - \alpha \right) \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2} & \frac{\left( \frac{s^2}{{\omega_0}^2} - \frac{\Omega^2}{{\omega_0}^2} + \alpha \right) \left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right) + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}{\left( \frac{s^2}{{\omega_0}^2} + 2 \xi \frac{s}{\omega_0} + 1 - \frac{{\Omega}^2}{{\omega_0}^2} \right)^2 + \left( 2 \frac{\Omega}{\omega_0} \frac{s}{\omega_0} \right)^2}
\end{bmatrix}
\end{equation}

# News terms with \alpha are added
# w0 and xi are the same as before => only the zeros are changing and not the poles.

** Effect of the Parallel Stiffness on the Plant Dynamics
# Negative Stiffness due to rotation => the stiffness should be larger than that

# For kp < negative stiffness => real zeros => non-minimum phase
# For kp > negative stiffness => complex conjugate zeros => minimum phase
\begin{equation}
  \begin{aligned}
    \alpha > \frac{\Omega^2}{{\omega_0}^2} \\
    \Leftrightarrow k_p > m \Omega^2
  \end{aligned}
\end{equation}

#+name: fig:plant_iff_kp
#+caption: Bode Plot of $f_u/F_u$ without parallel spring, with parallel springs with stiffness $k_p < m \Omega^2$ and $k_p > m \Omega^2$, $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/plant_iff_kp.pdf]]

# Location of the zeros as a function of kp => maybe to complex
# Do we talk about siso zeros of mimo (transmission zeros)?

# Try to show that we don't have anymore real zeros that was making the system non-minimum phase

# Show that it is the case on the root locus

#+name: fig:root_locus_iff_kp
#+caption: Root Locus for IFF without parallel spring, with parallel springs with stiffness $k_p < m \Omega^2$ and $k_p > m \Omega^2$, $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/root_locus_iff_kp.pdf]]

# For kp > m Omega => unconditionally stable

** Optimal Parallel Stiffness
# Attainable damping generally proportional to the distance between the poles and zeros (add reference, probably preumont)
# The zero is the poles of the system without the force sensors => w0 = sqrt(kp/m) +/- Omega ?? => seems not true
# Thus, small kp is wanted: kp close to m Omega^2 should give the optimal damping but is not acceptable for robustness reasons


# Large Stiffness decreases the attainable damping

# Example with kp = 5 m Omega

#+name: fig:root_locus_iff_kps_opt
#+caption: Root Locus for IFF when parallel stiffness is used, $\Omega = 0.1 \omega_0$
#+attr_latex: :environment subfigure :width 0.49\linewidth :align c
| file:figs/root_locus_iff_kps.pdf                 | file:figs/root_locus_opt_gain_iff_kp.pdf                                          |
| <<fig:root_locus_iff_kps>> Three values of $k_p$ | <<fig:root_locus_opt_gain_iff_kp>> $k_p = 5 m \Omega^2$, optimal damping is shown |

* Comparison of the Proposed Active Damping Techniques for Rotating Positioning Stages
<<sec:comparison>>
** Physical Comparison



** Attainable Damping

# Both techniques provides very good amount of damping

#+name: fig:comp_root_locus
#+caption: Root Locus for the three proposed decentralized active damping techniques: IFF with HFP, IFF with parallel springs, and relative DVF, $\Omega = 0.1 \omega_0$
#+attr_latex: :scale 1
[[file:figs/comp_root_locus.pdf]]

** Transmissibility and Compliance
# IFF with HPF and IFF with kp give very similar results!

# IFF degrades the compliance at low frequency (add reference)

# Passive Damping degrades the transmissibility at high frequency
# The roll-off is -1 instead of -2

#+name: fig:comp_active_damping
#+caption: Comparison of the two proposed Active Damping Techniques, $\Omega = 0.1 \omega_0$
#+attr_latex: :environment subfigure :width 0.45\linewidth :align c
| file:figs/comp_compliance.pdf            | file:figs/comp_transmissibility.pdf      |
| <<fig:comp_compliance>> Transmissibility | <<fig:comp_transmissibility>> Compliance |

* Conclusion
<<sec:conclusion>>

* Acknowledgment
:PROPERTIES:
:UNNUMBERED: t
:END:

* Bibliography                                                        :ignore:
\bibliography{ref.bib}
